### ISSUE TITLE
Need for more than 5 subject selections.

### ISSUE THREAD

**Issue by thecoldviews** [MayankVachher/kron#1]
People applying for an overload or TAship might need to check for clashes among more than 5 subjects.

**Comment by MayankVachher** [comment]
I'll add support for at most 10 subjects, would that suffice for overload?

I have other plans for TAship checking. Will add another enhancement for it.

**Comment by MayankVachher** [comment]
Added, in totality, 10 subject selections. Will work on the TA selection processes.
