### ISSUE TITLE
Feature which covers backlogs

### ISSUE THREAD

**Issue by SrishtiSengupta** [MayankVachher/kron#2]

**Comment by MayankVachher** [comment]
Does adding all the courses along with support for 10 subjects solve it? Let me know.

**Comment by SrishtiSengupta** [comment]
Of course not! 
I was thinking of something like having a dropdown with subjects of the previous semesters, from which one can choose whatever he/she wants to cover. Then these subjects chosen should also appear in the timetable along whatever was present in the original timetable.

**Comment by MayankVachher** [comment]
But if I add all the courses that are offered(even the first and second year mandatory courses), and include them in the timetable and give you the choice to select them with support of extra subject selections (up to 10 subjects), I think that emulates the behavior that you would like.

I would want the first and the second year students to also use it and print timetables. ._.

**Comment by SrishtiSengupta** [comment]
That would work (y)

**Comment by MayankVachher** [comment]
Solved.
