### ISSUE TITLE
Free days Busy Days

### ISSUE THREAD

**Issue by JuhiJetwani** [MayankVachher/kron#3]
Shows how many days you will be coming to college based on the selection. Can also show if first(/second) half is free on any day of the week.

**Comment by MayankVachher** [comment]
I didn't get you. Can you elaborate?

Do you mean just having the courses selected and nothing else in the table?

**Comment by JuhiJetwani** [comment]
No. I meant just put another div or something which displays which all days
of the week you don't have classes based on the selected courses. Fourth
years(/day scholars) usually like to keep a day or two free so that travel
nahi karna ho.
So I thought if you can just display which all days you will be free.

If you still have a doubt, just remove it. It isn't really that important.
